version: "3.9"

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 main.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - .env


